.users:
  title: Admin users
  apiAccess: true
  class: core/admin/users
  apiActions:
    validateSession:
      public: true
      params:
        session:
          description: 'Session'
          required: true
          type:
            name: string
    createUser:
      params:
        id:
          description: 'Id'
          required: true
          type:
            name: string
        password:
          description: 'Password MD5 hash'
          required: true
          type:
            name: string
  providerConfig:
    collection: users
  schema:
    fields:
      password:
        code: password
        title: Password
        type:
          name: string
      access:
        code: access
        title: Access
        type:
          name: array
          valueType:
            name: string
      developerMode:
        code: developerMode
        title: Developer mode
        type:
          name: bool
  model:
    class: core/admin/user
    apiAccess: true
    apiActions:
      login:
        public: true
        params:
          password:
            description: 'Password MD5 hash'
            required: true
            type:
              name: string

.sessions:
  class: core/storage/storage
  providerConfig:
    collection: sessions
  schema:
    fields:
      sessionId:
        code: sessionId
        title: SessionID
        type:
          name: string
      userId:
        code: userId
        title: User Id
        type:
          name: link
          storage: users

