.overlord:
  class: dweller
  .deploy:
    title: Deploy content
    class: modules/overlord/deploy
    apiAccess: true
    defaultApiAction: run
    apiActions:
      run:
        description: Constructs content and pushes it to repo
        params:
          adminMessage:
            title: Message
            code: adminMessage
            type:
              name: string
              textArea: true
    contentDir: ../content
