requiredModules:
  modules/overlord/rhai: true

.overlord:
  class: dweller
  .deploy:
    title: Deploy content
    class: modules/overlord/deploy
    apiAccess: true
    defaultApiAction: run
    apiActions:
      run:
        description: Constructs content and pushes it to repo
        params:
          adminMessage:
            title: Message
            code: adminMessage
            type:
              name: string
              textArea: true
    contentDir: ../content
.content:
  .parseOverlordSchema:
    class: modules/overlord/parseOverlordSchema
    apiAccess: true
    defaultApiAction: run
    apiActions:
      run:
        description: Create templates according to overlord schema
        params:
          schema:
            title: Schema
            code: schema
            type:
              name: json
