requiredModules:
  modules/overlord/rhai: true

.overlord:
  class: dweller
  .deploy:
    title: Deploy content
    class: modules/overlord/deploy
    apiAccess: true
    defaultApiAction: run
    apiActions:
      run:
        description: Constructs content and pushes it to repo
        params:
          adminMessage:
            title: Message
            code: adminMessage
            type:
              name: string
              textArea: true
    contentDir: ../tmp/content
.content:
  .parseOverlordSchema:
    class: modules/overlord/parseOverlordSchema
    apiAccess: true
    defaultApiAction: run
    apiActions:
      run:
        description: Create templates according to overlord schema
        params:
          schema:
            title: Schema
            code: schema
            type:
              name: json
          targets:
            title: Targets
            code: targets
            type:
              name: array
              valueType:
                name: link
                storageId: content.construct.targets

.resourceSystem:
  .extract:
    providers:
      overlordGit: true
    .overlordGit:
      apiAccess: false
      class: modules/overlord/gitResources
      repoDir: ../tmp/overlord
      resourcesRoot: overlord/frontend/ui/public
      publicResDir: ../tmp/public/resources


