datatypes:
  typedef:
    title: Type definition
    params:
      allowedTypes:
        title: Allowed types
        type:
          name: array
          valueType:
            name: string
  bool:
    title: Boolean
  number:
    title: Number
    params:
      integer:
        title: Integer
        type:
          name: bool
  string:
    title: String
    params:
      textArea:
        title: Multiline
        type:
          name: bool
      translated:
        title: Translated
        type:
          name: bool
  link:
    title: Storage link
    params:
      storageId:
        title: Storage Id
        type:
          name: string
  json:
    title: JSON
  array:
    title: Array
    params:
      valueType:
        title: Value type
        required: true
        type:
          name: typedef
          allowedTypes:
            - number
            - link
            - string
            - json
  select:
    title: Select
    params:
      options:
        title: Options
        type:
          name: array
  script:
    title: Script
    params:
      language:
        title: Language
        type:
          name: string
  enum:
    title: Enum
    params:
      values:
        title: Values
        type:
          name: array
          valueType:
            name: string
      valueTitles:
        title: Value titles
        type:
          name: array
          valueType:
            name: string
  resource:
    title: Resource
    params:
      resourceType:
        title: Resource type
        type:
          name: enum
          values:
            - webp
  struct:
    title: Struct
    params:
      fields:
        title: Fields
        type:
          name: array
          valueType:
            name: struct
            fields:
              - code: code
                title: Code
                type:
                  name: string
              - code: title
                title: Title
                type:
                  name: string
              - code: type
                title: Type
                type:
                  name: typedef
              - code: description
                title: Description
                type:
                  name: string
                  textArea: true
