.content:
  class: modules/content/content
  apiActions:
    dump:
      description: Dumps content
    restore:
      description: Restores content
      params: 
        content:
          type: json
          description: Content to restore
  .templates:
    class: modules/content/templates
    apiActions:
      createTemplate:
        params:
          templateId:
            type:
              name: string
            description: New template ID
      create: false
      clone: false
    providerConfig:
      collection: templates
    schema:
      objectTitle: '{title}'
      fields:
        title:
          code: title
          title: Title
          type:
            name: string
        objectTitle:
          code: objectTitle
          title: Object title
          type:
            name: string
    model:
      apiActions:
        delete: false
      .params:
        class: core/storage/storage
        forceMyParentIdInModels: templateId
        providerConfig:
          collection: templateParams
        schema:
          fields:
            title:
              code: title
              title: Title
              type:
                name: string
            code:
              code: code
              title: Code
              type:
                name: string
            type:
              readonly: true
              code: type
              title: Type
              type:
                name: typedef
      .objects:
        class: core/storage/model
        forceMyParentIdInModels: templateId
        providerConfig:
          collection: objects
        model:
          class: modules/content/object
