requiredModules:
  modules/content/construct: true

.content:
  class: modules/content/content
  apiActions:
    dump:
      description: Dumps content
    restore:
      description: Restores content
      params: 
        content:
          type: json
          description: Content to restore
  .templates:
    apiAccess: true
    title: Content templates
    class: modules/content/templates
    apiActions:
      createTemplate:
        params:
          templateId:
            type:
              name: string
            description: New template ID
      create: false
    providerConfig:
      collection: templates
    schema:
      modelTitle: '{values.title}'
      fields:
        title:
          code: title
          title: Title
          type:
            name: string
        modelTitle:
          code: modelTitle
          title: Object title
          type:
            name: string
    model:
      apiAccess: true
      apiActions:
        delete: false
      .params:
        apiAccess: true
        model:
          class: modules/content/templateParam
          apiAccess: true
        class: modules/content/templateParams
        forceMyParentIdInModels: templateId
        providerConfig:
          collection: templateParams
        schema:
          fields:
            title:
              code: title
              title: Title
              type:
                name: string
            code:
              code: code
              title: Code
              type:
                name: string
            type:
              readonly: true
              code: type
              title: Type
              type:
                name: typedef
      .objects:
        apiAccess: true
        class: modules/content/objects
        forceMyParentIdInModels: templateId
        providerConfig:
          collection: objects
        model:
          apiAccess: true
          class: modules/content/object

datatypes:
  number:
    allowInContent: true
  bool:
    allowInContent: true
  json:
    allowInContent: true
  array:
    allowInContent: true
  string:
    allowInContent: true
  clink:
    title: Content Link
    allowInContent: true
    params:
      templateId:
        title: Template
        required: true
        type:
          name: link
          storageId: content.templates
  contentValueSource:
    title: Source

