.content:
  class: modules/content/content
  apiActions:
    dump:
      description: Dumps content
    restore:
      description: Restores content
      params: 
        content:
          type: json
          description: Content to restore
  .templateParams:
    class: core/storage/storage
    prohibitApiAccess: true
    providerConfig:
      collection: templateParams
    schema:
      fields:
        title:
          code: title
          title: Title
          type:
            name: string
        code:
          code: code
          title: Code
          type:
            name: string
        type:
          readonly: true
          code: type
          title: Type
          type:
            name: typedef
  .templates:
    class: modules/content/templates
    apiActions:
      createTemplate:
        params:
          templateId:
            type:
              name: string
            description: New template ID
      create: false
    providerConfig:
      collection: templates
    schema:
      objectTitle: '{title}'
      fields:
        title:
          code: title
          title: Title
          type:
            name: string
        objectTitle:
          code: objectTitle
          title: Object title
          type:
            name: string
    model:
      .params:
        class: core/storage/storage
        forceMyParentIdInModels: templateId
        providerConfig:
          collection: templateParams
        schema:
          provider: content.templateParams
      .objects:
        class: modules/content/objects
        forceMyParentIdInModels: templateId
        providerConfig:
          collection: objects
        model:
          class: modules/content/object
