requiredModules:
  core/datatypes: true
  core/mongo: true
  core/storage: true
  core/admin: true
  core/api: true
  core/vars: true
  core/projectConfig: true

  modules/content: true
  modules/translations: true

  modules/overlord: true
  # modules/adventure: true

.storageProviders:
  .mongo:
    db: adventure_test
  .mongoMemory:
    db: adventure_test

dweller:
  apiActions:
    help:
      description: Shows help
    getConfig:
      description: Shows config
