requiredModules:
  core/datatypes: true
  modules/content: true
  core/mongo: true
  core/storage: true
  core/admin: true
  core/api: true
  core/projectConfig: true

.storageProviders:
  .mongo:
    db: overlord_test
  .mongoMemory:
    db: overlord_test

dweller:
  apiActions:
    help:
      description: Shows help
    getConfig:
      description: Shows config
