.content:
  .construct:
    title: Content constuct
    class: modules/content/construct/construct
    defaultValueConstructor: base
    apiAccess: true
    defaultApiAction: run
    apiActions:
      run:
        description: Constructs content for a given target
        params:
          targetId:
            required: true
            title: Target Id
            code: targetId
            type:
              name: link
              storageId: content.construct.targets
    .targets:
      apiAccess: true
      title: Content targets
      class: core/storage/storage
      providerConfig:
        collection: contentTargets
      schema:
        modelTitle: '{values.title}'
        fields:
          title:
            title: Title
            code: title
            type:
              name: string
          templatesAsArray:
            title: Construct templates as array
            code: templatesAsArray
            type:
              name: bool

      models:
        apiAccess: true
    .constructors:
      class: dweller
      .link:
        class: modules/content/construct/datatypes/link
      .base:
        class: modules/content/construct/datatypes/base

  .templates:
    schema:
      fields:
        targets:
          title: Construct targets
          code: targets
          type:
            name: array
            valueType:
              name: link
              storageId: content.construct.targets
    model:
      .params:
        schema:
          fields:
            targets:
              title: Construct targets
              code: targets
              type:
                name: array
                valueType:
                  name: link
                  storageId: content.construct.targets

datatypes:
  clink:
    valueConstructor: clink
    params:
      inline:
        title: Inline
        type:
          name: bool
