.content:
  .targets:
    title: Content targets
    apiAccess: true
    class: core/storage/storage
    providerConfig:
      collection: contentTargets
    schema:
      fields:
        title:
          title: Title
          code: title
          type:
            name: string
    model:
      class: modules/content/construct/target
      apiAccess: true
      apiActions:
        construct:
          description: 'Returns constructed content for the target'
  .templates:
    model:
      .params:
        schema:
          fields:
            targets:
              title: Construct targets
              code: targets
              type:
                name: array
                valueType:
                  name: link
                  storageId: content.targets


