.content:
  .construct:
    title: Content constuct
    class: modules/content/construct/construct
    defaultValueConstructor: base
    apiAccess: true
    defaultApiAction: run
    apiActions:
      run:
        description: Constructs content for a given target
        params:
          targetId:
            required: true
            title: Target Id
            code: targetId
            type:
              name: link
              storageId: content.construct.targets
    .targets:
      apiAccess: true
      title: Content targets
      class: modules/content/construct/targets
      providerConfig:
        collection: contentTargets
      schema:
        modelTitle: '{values.title}'
        fields:
          title:
            title: Title
            code: title
            type:
              name: string
          templatesAsArray:
            title: Construct templates as array
            code: templatesAsArray
            type:
              name: bool
          defaultEmptyFields:
            title: Устанавливать дефолтные значения для пустых полей
            code: defaultEmptyFields
            type:
              name: bool

      model:
        apiAccess: true
      apiActions:
        createTarget:
          params:
            targetId:
              type:
                name: string
              description: New target ID
        create: false
    .constructors:
      class: dweller
      .clink:
        class: modules/content/construct/datatypes/clink
      .base:
        class: modules/content/construct/datatypes/base
      .struct:
        class: modules/content/construct/datatypes/struct
      .array:
        class: modules/content/construct/datatypes/array
      .number:
        class: modules/content/construct/datatypes/number
      .bool:
        class: modules/content/construct/datatypes/bool
      .resource:
        class: modules/content/construct/datatypes/resource


  .templates:
    schema:
      fields:
        targets:
          title: Construct targets
          code: targets
          type:
            name: array
            valueType:
              name: link
              storageId: content.construct.targets
    model:
      .params:
        schema:
          fields:
            targets:
              title: Construct targets
              code: targets
              type:
                name: array
                valueType:
                  name: link
                  storageId: content.construct.targets

datatypes:
  clink:
    valueConstructor: clink
  struct:
    valueConstructor: struct
  number:
    valueConstructor: number
  bool:
    valueConstructor: bool
  array:
    valueConstructor: array
  resource:
    valueConstructor: resource
