.content:
  .targets:
    title: Content targets
    apiAccess: true
    class: core/storage/storage
    providerConfig:
      collection: contentTargets
    schema:
      fields:
        title:
          title: Title
          code: title
          type:
            name: string
    model:
      class: modules/content/construct/target
      apiAccess: true
      apiActions:
        construct:
          description: 'Returns constructed content for the target'
  .construct:
    apiAccess: true
    class: content/construct/construct
    defaultApiAction: run
    apiActions:
      run:
        description: 'Constructs content'
  .constructed:
    apiAccess: true
    class: core/storage/storage
    providerConfig:
      collection: constructedContent
